♻️ test: 깃허브 액션 , eb 테스트 - 21번째 - .ebextensions 있는지 확인 🔗 Resolves: #98

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -59,6 +59,14 @@ jobs:
       - name: Show Current Time
         run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"
 
+      - name: Check .ebextensions before copying
+        run: |
+          if [ -d ".ebextensions" ]; then
+            echo ".ebextensions exists."
+          else
+            echo "Error: .ebextensions directory is missing!"
+            exit 1
+          fi
       # EB에 CD 하기 위해 추가 작성
       - name: Generate deployment package
         run: |
